---
# tasks file for centos7
- name: Set hostname
  command: hostnamectl set-hostname {{ hostname }}

- name: Config /etc/hosts
  template:
    src: hosts.j2
    dst: /etc/hosts

- name: Set timezone
  command: timedatectl set-timezone Asia/Ho_Chi_Minh

- name: Update!!!
  yum: 
    name: *
    state: latest

- name: Install requirement app
  yum:
    name:
      - firewalld
      - git
      - mc
      - htop
      - nano
      - perl-CPAN
      - https://centos7.iuscommunity.org/ius-release.rpm
      - mariadb-devel
      - gcc
      - python36u
      - python36u-devel
      - vim
    state: present
- name: Enable firewalld
  service:
    name: firewalld
    state: enabled

- name: Config CPAN
  expect:
    command: cpan
    responses:
      - sudo

- name: Enable firewalld
  service:
    name: firewalld
    enabled: true

- name: Config SELINUX
  template:
    src: selinux.j2
    dest: /etc/selinux/config

- name: Reboot
  reboot:
