---
# tasks file for centos7
- name: Set hostname
  command: hostnamectl set-hostname {{ hostname }}

- name: Config /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: display ip-address
  debug: msg={{ ansible_all_ipv4_addresses | ipaddr }}

- name: Set timezone
  command: timedatectl set-timezone Asia/Ho_Chi_Minh

- name: Update!!!
  yum: 
    name: "*"
    state: latest

- name: Install requirement app
  yum:
    name: "{{ required_packages }}"
    state: present

#- name: Config CPAN
#  expect:
#    command: cpan
#    responses:
#      - sudo

- name: Enable firewalld
  service:
    name: firewalld
    enabled: true

- name: Config SELINUX
  template:
    src: selinux.j2
    dest: /etc/selinux/config

- name: Reboot
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0

- name: wait for 10 seconds
  pause:
    seconds: 10

- name: wait for the system to reboot
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 60

- name: FW config - allow services
  firewalld:
    #zone: work
    service: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - http

- name: FW config - allow ports
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop: "{{ fw_ports }}"

- name: Reload FW
  service:
    name: firewalld
    state: reloaded