---
# tasks file for centos7
- name: Set hostname
  command: hostnamectl set-hostname {{ hostname }}

- name: Config /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Set timezone
  command: timedatectl set-timezone Asia/Ho_Chi_Minh

- name: Update!!!
  yum: 
    name: "*"
    state: latest

- name: Install requirement app
  yum:
    name: {{ required_app }}
    state: present
- name: Enable firewalld
  service:
    name: firewalld
    state: enabled

- name: Config CPAN
  expect:
    command: cpan
    responses:
      - sudo

- name: Enable firewalld
  service:
    name: firewalld
    enabled: true

- name: Config SELINUX
  template:
    src: selinux.j2
    dest: /etc/selinux/config

- name: Reboot
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0

- name: wait for 10 seconds
  pause:
    seconds: 10

- name: wait for the system to reboot
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 60

