# roles/mariadb/tasks/install.yml
- name: Install MariaDB
  yum:
    name:
      - MariaDB-server
	    - MariaDB-client
	    - MariaDB-common
	    - MariaDB-backup
    state: present

- name: Enable MariaDB
  service:
    name: mariadb
    enabled: true

- name: Start MariaDB
  service:
    name: mariadb
    state: started