# roles/mariadb/tasks/install.yml
- name: Install MariaDB repo
  template:
    src: MariaDB.repo
    dest: /etc/yum.repos.d/MariaDB.repo
    
- name: Install MariaDB
  yum:
    name:
      - MariaDB-server
      - MariaDB-client
      - MariaDB-common
      - MariaDB-backup
    state: present

- name: Enable MariaDB
  service:
    name: mariadb
    enabled: true

- name: Start MariaDB
  service:
    name: mariadb
    state: started