---
# tasks file for icinga2
- name: add repo icinga-rpm
  yum:
    name: https://packages.icinga.com/epel/icinga-rpm-release-7-latest.noarch.rpm
    state: present

- name: group install
  command: yum group install -y "Development Tools"

- name: install perl modules
  yum:
    name: "{{ perl_modules }}"
    state: present

- name: install lib for vmware
  yum:
    name: "{{ vmware_lib }}"
    state: present

# Install Java
- name: Install Oracle Java
  yum:
    name: "java-latest-openjdk"
    state: present

# CPAN Modules
- name: install App::cpanminus
  command: cpan App::cpanminus

- name: install cpan modules
  cpanm:
    name: "{{ item }}"
    notest: true
  loop: "{{ cpan_modules }}" 

# Install icinga2
- name: Install icinga2
  yum:
    name:
      - icinga2
      - nagios-plugins-all
      - nagios-plugins-nrpe
    state: present

# Plugin
# Install Centreon Plugin
- name: Create plugin thirdparty directory
  file:
    path: "{{ plugin_dir }}/thirdparty"
    state: directory

- name: Clone Centreon plugin from git
  git:
    repo: https://github.com/centreon/centreon-plugins.git
    dest: "{{ plugin_dir }}/thirdparty/centreon-plugins"

- name: change permission for centreon plugin
  file:
    path: "{{ plugin_dir }}/thirdparty/centreon-plugins/centreon_plugins.pl"
    mode: 0755

- name: Create  centplugins directory
  file:
    path: /var/lib/centreon/centplugins
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_user }}"
    state: directory

# Install check_wmi_plug
#- name: Prepare for wmi Installation 
  #command: rpm -Uvh http://www6.atomicorp.com/channels/atomic/centos/7/x86_64/RPMS/atomic-release-1.0-21.el7.art.noarch.rpm
#
#- name: install wmi
  #yum:
    #name: wmi
    #state: present
#
#- name: clone check_wmi_plus from git
  #git:
    #repo: https://github.com/speartail/checkwmiplus.git
    #dest: {{ plugin_dir }}

# Install check_nwc_health
#- name: Install check_nwc_health
#  unarchive:
#    src: https://labs.consol.de/assets/downloads/nagios/check_nwc_health-7.12.1.2.tar.gz
#    dest: {{ plugin_dir }}

# VMware sdk

# Install check_vmware plugin

# Install check_jmx plugin

# Install monitor plugin
